[[redirects]]
from = "/"
to = "/home.html"
status = 200
force = true

[build]
  command = "cp public/custom-head.html public/custom-head.html && cp -r src/notes public/notes"
  publish = "public"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
