[[redirects]]
from = "/"
to = "/home.html"
status = 200
force = true

[build]
  command = "cp -r src/notes public/notes && cp -r src/lib/styles public/lib/styles"
  publish = "public"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
