[build]
  publish = "my-digital-garden/public"
  command = """
  mkdir -p my-digital-garden/public &&
  rsync -av --exclude=my-digital-garden my-digital-garden/ my-digital-garden/public/
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
